"""Persistent global IPv4 forwarding helpers."""

from __future__ import annotations

import argparse
import json
import platform
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


APP_DIR = Path("/etc/py-nic-manager")
STATE_FILE = APP_DIR / "global-forwarding.json"
LINUX_SERVICE_FILE = Path("/etc/systemd/system/py-nic-manager-global-forwarding.service")
SYSCTL_FILE = Path("/etc/sysctl.d/99-py-nic-manager-global-forwarding.conf")


def set_global_forwarding(enabled: bool) -> None:
    """Apply Linux global IPv4 forwarding now and keep it after reboot."""
    _ensure_linux()
    save_state(enabled)
    write_sysctl_config(enabled)
    apply_state()
    install_startup_hook()


def load_state() -> bool:
    try:
        data = json.loads(STATE_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    if not isinstance(data, dict):
        return False
    return _coerce_bool(data.get("enabled", False))


def save_state(enabled: bool) -> None:
    APP_DIR.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(
        json.dumps({"enabled": bool(enabled)}, indent=2, sort_keys=True),
        encoding="utf-8",
    )


def apply_state() -> None:
    _ensure_linux()
    value = "1" if load_state() else "0"
    _run(["sysctl", "-w", f"net.ipv4.ip_forward={value}"])


def write_sysctl_config(enabled: bool) -> None:
    _ensure_linux()
    value = "1" if enabled else "0"
    SYSCTL_FILE.parent.mkdir(parents=True, exist_ok=True)
    SYSCTL_FILE.write_text(
        "# Generated by Py NIC Manager.\n"
        "# Keeps Linux global IPv4 forwarding in sync after reboot.\n"
        f"net.ipv4.ip_forward = {value}\n",
        encoding="utf-8",
    )


def install_startup_hook() -> None:
    _ensure_linux()
    if not shutil.which("systemctl"):
        raise RuntimeError(
            "systemctl is required to keep Linux global IPv4 forwarding persistent after reboot."
        )
    service = f"""[Unit]
Description=Py NIC Manager persistent global IPv4 forwarding
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart={shlex.quote(sys.executable)} -m py_nic_manager.global_forwarding apply
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
"""
    LINUX_SERVICE_FILE.parent.mkdir(parents=True, exist_ok=True)
    LINUX_SERVICE_FILE.write_text(service, encoding="utf-8")
    _run(["systemctl", "daemon-reload"])
    _run(["systemctl", "enable", "--now", LINUX_SERVICE_FILE.name])


def _coerce_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "enabled", "on"}


def _run(command: list[str]) -> None:
    completed = subprocess.run(command, capture_output=True, check=False, text=True)
    if completed.returncode != 0:
        output = (completed.stderr or completed.stdout).strip()
        raise RuntimeError(output or "Command failed: " + " ".join(command))


def _ensure_linux() -> None:
    if platform.system().lower() != "linux":
        raise RuntimeError("Linux global IPv4 forwarding persistence is only available on Linux.")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Manage persistent Linux global IPv4 forwarding.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    set_parser = subparsers.add_parser("set", help="Set global IPv4 forwarding.")
    set_parser.add_argument("state", choices=["enabled", "disabled"])
    subparsers.add_parser("apply", help="Apply the saved global IPv4 forwarding state.")
    subparsers.add_parser("install", help="Install the systemd startup hook.")

    args = parser.parse_args(argv)
    try:
        if args.command == "set":
            set_global_forwarding(args.state == "enabled")
            print(f"Linux global IPv4 forwarding {args.state}.")
        elif args.command == "apply":
            apply_state()
            print("Linux global IPv4 forwarding state applied.")
        elif args.command == "install":
            install_startup_hook()
            print("Linux global IPv4 forwarding startup hook installed.")
        return 0
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
