from __future__ import annotations

import argparse
import json
import os
import platform
import re
import subprocess
import sys
from pathlib import Path


ANCHOR_FILE = Path("/etc/pf.anchors/py-nic-manager-forwarding")
APP_DIR = Path("/Library/Application Support/PyNICManager")
STATE_FILE = APP_DIR / "macos-forwarding-disabled.json"
COM_APPLE_ANCHOR = "com.apple/py-nic-manager-forwarding"
FALLBACK_ANCHOR = "py-nic-manager-forwarding"
PF_CONF = Path("/etc/pf.conf")
INTERFACE_RE = re.compile(r"^[A-Za-z0-9_.:-]+$")


def set_interface_forwarding(interface: str, enabled: bool) -> None:
    _ensure_macos()
    clean_interface = _validate_interface(interface)
    disabled = load_disabled_interfaces()

    if enabled:
        if not global_forwarding_enabled():
            disabled.update(_all_interfaces())
        disabled.discard(clean_interface)
        _run(["sysctl", "-w", "net.inet.ip.forwarding=1"])
    else:
        disabled.add(clean_interface)

    save_disabled_interfaces(disabled)
    _write_anchor_rules(disabled)
    _load_pf_anchor()


def global_forwarding_enabled() -> bool:
    result = _run(["sysctl", "-n", "net.inet.ip.forwarding"])
    return result.strip() == "1"


def load_disabled_interfaces() -> set[str]:
    try:
        data = json.loads(STATE_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return set()
    values = data.get("disabled_interfaces", [])
    return {_validate_interface(str(item)) for item in values}


def save_disabled_interfaces(disabled_interfaces: set[str]) -> None:
    APP_DIR.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(
        json.dumps({"disabled_interfaces": sorted(disabled_interfaces)}, indent=2),
        encoding="utf-8",
    )


def _write_anchor_rules(disabled_interfaces: set[str]) -> None:
    lines = [
        "# Generated by Py NIC Manager.",
        "# Blocks IPv4 packets that entered selected interfaces and would be forwarded out.",
    ]
    for interface in sorted(disabled_interfaces):
        lines.append(f"block drop out quick inet received-on {interface}")
    ANCHOR_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _load_pf_anchor() -> None:
    anchor = _active_anchor_name()
    _run(["pfctl", "-a", anchor, "-f", str(ANCHOR_FILE)])
    _run(["pfctl", "-E"], allow_failure_text="pf already enabled")


def _active_anchor_name() -> str:
    try:
        pf_conf = PF_CONF.read_text(encoding="utf-8", errors="replace")
    except OSError:
        pf_conf = ""
    if 'anchor "com.apple/*"' in pf_conf:
        return COM_APPLE_ANCHOR
    _ensure_fallback_anchor(pf_conf)
    return FALLBACK_ANCHOR


def _ensure_fallback_anchor(pf_conf: str) -> None:
    if f'anchor "{FALLBACK_ANCHOR}"' in pf_conf:
        return
    block = (
        "\n# Py NIC Manager forwarding controls\n"
        f'anchor "{FALLBACK_ANCHOR}"\n'
        f'load anchor "{FALLBACK_ANCHOR}" from "{ANCHOR_FILE}"\n'
    )
    with PF_CONF.open("a", encoding="utf-8") as handle:
        handle.write(block)
    _run(["pfctl", "-f", str(PF_CONF)])


def _all_interfaces() -> set[str]:
    result = _run(["ifconfig", "-l"])
    return {_validate_interface(item) for item in result.split() if item and item != "lo0"}


def _validate_interface(interface: str) -> str:
    value = interface.strip()
    if not value or not INTERFACE_RE.match(value):
        raise RuntimeError(f"Invalid network interface name: {interface!r}")
    return value


def _run(command: list[str], *, allow_failure_text: str = "") -> str:
    completed = subprocess.run(command, capture_output=True, check=False)
    stdout = _decode(completed.stdout).strip()
    stderr = _decode(completed.stderr).strip()
    if completed.returncode != 0:
        combined = f"{stdout}\n{stderr}".strip()
        if allow_failure_text and allow_failure_text.lower() in combined.lower():
            return stdout
        raise RuntimeError(combined or f"{' '.join(command)} failed with exit code {completed.returncode}.")
    return stdout


def _decode(data: bytes) -> str:
    for encoding in ("utf-8", "utf-8-sig"):
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            continue
    return data.decode("utf-8", errors="replace")


def _ensure_macos() -> None:
    if platform.system().lower() != "darwin":
        raise RuntimeError("macOS forwarding control is only available on macOS.")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Manage Py NIC Manager macOS forwarding rules.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    set_parser = subparsers.add_parser("set", help="Set forwarding behavior for an interface.")
    set_parser.add_argument("interface")
    set_parser.add_argument("state", choices=["enabled", "disabled"])
    subparsers.add_parser("list", help="Print interfaces blocked by Py NIC Manager.")
    args = parser.parse_args(argv)

    try:
        if args.command == "set":
            set_interface_forwarding(args.interface, args.state == "enabled")
            print(f"IPv4 router forwarding {args.state} for {args.interface}.")
        elif args.command == "list":
            print(json.dumps(sorted(load_disabled_interfaces())))
        return 0
    except Exception as exc:
        print(str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
