from __future__ import annotations

import argparse
import json
import platform
import re
import shutil
import subprocess
from pathlib import Path


TTL_EXCEEDED_RULE_PREFIX = "py-nic-manager-ttl-exceeded"
MACOS_ANCHOR_FILE = Path("/etc/pf.anchors/py-nic-manager-ttl-exceeded")
MACOS_APP_DIR = Path("/Library/Application Support/PyNICManager")
MACOS_STATE_FILE = MACOS_APP_DIR / "macos-ttl-exceeded-disabled.json"
MACOS_COM_APPLE_ANCHOR = "com.apple/py-nic-manager-ttl-exceeded"
MACOS_FALLBACK_ANCHOR = "py-nic-manager-ttl-exceeded"
MACOS_PF_CONF = Path("/etc/pf.conf")
INTERFACE_RE = re.compile(r"^[A-Za-z0-9_.:-]+$")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Manage Py NIC Manager TTL-exceeded ICMP rules.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    set_parser = subparsers.add_parser("set", help="Enable or disable TTL-exceeded ICMP replies for an interface.")
    set_parser.add_argument("interface")
    set_parser.add_argument("state", choices=["enabled", "disabled"])
    args = parser.parse_args(argv)

    if args.command == "set":
        return set_ttl_exceeded_icmp(args.interface, enabled=args.state == "enabled")
    parser.error("Unsupported command.")
    return 2


def set_ttl_exceeded_icmp(interface: str, *, enabled: bool) -> int:
    system = platform.system().lower()
    if system == "linux":
        return _set_linux_ttl_exceeded_icmp(interface, enabled=enabled)
    if system == "darwin":
        _set_macos_ttl_exceeded_icmp(interface, enabled=enabled)
        return 0
    raise SystemExit("The ttl_exceeded helper supports Linux and macOS.")


def _set_linux_ttl_exceeded_icmp(interface: str, *, enabled: bool) -> int:
    iptables = shutil.which("iptables")
    if not iptables:
        raise SystemExit("iptables is required to manage TTL-exceeded ICMP behavior on Linux.")

    rule = [
        "-i",
        interface,
        "-m",
        "ttl",
        "--ttl-eq",
        "1",
        "-m",
        "addrtype",
        "!",
        "--dst-type",
        "LOCAL",
        "-m",
        "comment",
        "--comment",
        f"{TTL_EXCEEDED_RULE_PREFIX}:{interface}",
        "-j",
        "DROP",
    ]
    exists = _run([iptables, "-t", "mangle", "-C", "PREROUTING", *rule]).returncode == 0
    if enabled:
        while exists:
            deleted = _run([iptables, "-t", "mangle", "-D", "PREROUTING", *rule], check=True)
            if deleted.returncode != 0:
                return deleted.returncode
            exists = _run([iptables, "-t", "mangle", "-C", "PREROUTING", *rule]).returncode == 0
        return 0
    if exists:
        return 0
    return _run([iptables, "-t", "mangle", "-A", "PREROUTING", *rule], check=True).returncode


def load_macos_disabled_interfaces() -> set[str]:
    try:
        data = json.loads(MACOS_STATE_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return set()
    values = data.get("disabled_interfaces", [])
    return {_validate_interface(str(item)) for item in values}


def _set_macos_ttl_exceeded_icmp(interface: str, *, enabled: bool) -> None:
    clean_interface = _validate_interface(interface)
    disabled = load_macos_disabled_interfaces()
    if enabled:
        disabled.discard(clean_interface)
    else:
        disabled.add(clean_interface)
    _save_macos_disabled_interfaces(disabled)
    _write_macos_anchor_rules(disabled)
    _load_macos_pf_anchor()


def _save_macos_disabled_interfaces(disabled_interfaces: set[str]) -> None:
    MACOS_APP_DIR.mkdir(parents=True, exist_ok=True)
    MACOS_STATE_FILE.write_text(
        json.dumps({"disabled_interfaces": sorted(disabled_interfaces)}, indent=2),
        encoding="utf-8",
    )


def _write_macos_anchor_rules(disabled_interfaces: set[str]) -> None:
    MACOS_ANCHOR_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by Py NIC Manager.",
        "# Blocks outbound ICMPv4 Time Exceeded replies on selected interfaces.",
    ]
    for interface in sorted(disabled_interfaces):
        lines.append(f"block drop out quick on {interface} inet proto icmp icmp-type 11")
    MACOS_ANCHOR_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _load_macos_pf_anchor() -> None:
    anchor = _macos_anchor_name()
    _run(["pfctl", "-a", anchor, "-f", str(MACOS_ANCHOR_FILE)], check=True)
    _run(["pfctl", "-E"])


def _macos_anchor_name() -> str:
    try:
        pf_conf = MACOS_PF_CONF.read_text(encoding="utf-8", errors="replace")
    except OSError:
        pf_conf = ""
    if 'anchor "com.apple/*"' in pf_conf:
        return MACOS_COM_APPLE_ANCHOR
    _ensure_macos_fallback_anchor(pf_conf)
    return MACOS_FALLBACK_ANCHOR


def _ensure_macos_fallback_anchor(pf_conf: str) -> None:
    if f'anchor "{MACOS_FALLBACK_ANCHOR}"' in pf_conf:
        return
    block = (
        "\n# Py NIC Manager TTL-exceeded ICMP controls\n"
        f'anchor "{MACOS_FALLBACK_ANCHOR}"\n'
        f'load anchor "{MACOS_FALLBACK_ANCHOR}" from "{MACOS_ANCHOR_FILE}"\n'
    )
    with MACOS_PF_CONF.open("a", encoding="utf-8") as handle:
        handle.write(block)
    _run(["pfctl", "-f", str(MACOS_PF_CONF)], check=True)


def _validate_interface(interface: str) -> str:
    value = interface.strip()
    if not value or not INTERFACE_RE.match(value):
        raise SystemExit(f"Invalid network interface name: {interface!r}")
    return value


def _run(command: list[str], *, check: bool = False) -> subprocess.CompletedProcess[str]:
    completed = subprocess.run(command, text=True, capture_output=True, check=False)
    if check and completed.returncode != 0:
        message = (completed.stderr or completed.stdout).strip()
        if message:
            raise SystemExit(message)
        raise SystemExit(f"Command failed: {' '.join(command)}")
    return completed


if __name__ == "__main__":
    raise SystemExit(main())
